org: onlyuml
service: diagrams-serverless

provider:
  name: aws
  runtime: python3.12
  region: us-east-1
  timeout: 29
  iam:
    role: arn:aws:iam::902996284231:role/LabRole

plugins:
  - serverless-python-requirements

custom:
  pythonRequirements:
    dockerizePip: true
    layer: true

functions:
  RegisterUser:
    handler: user/RegisterUser.lambda_handler
    events:
      - http:
          path: user/register
          method: post
          cors: true
          integration: lambda-proxy
    timeout: 29

  LoginUsuario:
    handler: user/LoginUsuario.lambda_handler
    events:
      - http:
          path: user/login
          method: post
          cors: true
          integration: lambda-proxy
    timeout: 29

  VerifyToken:
    handler: user/VerifyToken.lambda_handler
    events:
      - http:
          path: user/verify
          method: post
          cors: true
          integration: lambda-proxy
    timeout: 29
  WithJSON:
    handler: diagrams/WithJSON.lambda_handler
    layers:
      - arn:aws:lambda:us-east-1:902996284231:layer:layer-diagrams:1
    events:
      - http:
          path: diagrams/with-json
          method: post
          cors: true
          integration: lambda-proxy
    timeout: 29
  PreflightLogin:
    handler: user/Preflight.lambda_handler
    events:
      - http:
          path: user/login
          method: options
          cors: true

  PreflightRegister:
    handler: user/Preflight.lambda_handler
    events:
      - http:
          path: user/register
          method: options
          cors: true

  PreflightVerify:
    handler: user/Preflight.lambda_handler
    events:
      - http:
          path: user/verify
          method: options
          cors: true
