org: onlyuml
service: diagrams-serverless

provider:
  name: aws
  runtime: python3.12
  region: us-east-1
  timeout: 29  # Aplica como valor por defecto
  iam:
    role: arn:aws:iam::902996284231:role/LabRole  # Usa un rol existente que ya tengas permiso para usar

functions:
  RegisterUser:
    handler: user/RegisterUser.lambda_handler
    events:
      - http:
          path: user/register
          method: post
          cors: 
            origin: http://localhost:5173  # <--- especifica tu frontend
            credentials: true              # <--- habilita credenciales
          integration: lambda
    timeout: 29

  LoginUsuario:
    handler: user/LoginUsuario.lambda_handler
    events:
      - http:
          path: user/login
          method: post
          cors: true
          integration: lambda
    timeout: 29

  VerifyToken:
    handler: user/VerifyToken.lambda_handler
    events:
      - http:
          path: user/verify
          method: post
          cors: true
          integration: lambda
    timeout: 29
