org: onlyuml
service: diagrams-serverless

provider:
  name: aws
  runtime: python3.12
  region: us-east-1
  timeout: 29
  iam:
    role: arn:aws:iam::902996284231:role/LabRole

functions:
  RegisterUser:
    handler: user/RegisterUser.lambda_handler
    events:
      - http:
          path: user/register
          method: post
          cors: http://localhost:5173
          integration: lambda
    timeout: 29

  LoginUsuario:
    handler: user/LoginUsuario.lambda_handler
    events:
      - http:
          path: user/login
          method: post
          cors: http://localhost:5173
          integration: lambda
    timeout: 29

  VerifyToken:
    handler: user/VerifyToken.lambda_handler
    events:
      - http:
          path: user/verify
          method: post
          cors: http://localhost:5173
          integration: lambda
    timeout: 29

  PreflightLogin:
    handler: user/Preflight.lambda_handler
    events:
      - http:
          path: user/login
          method: options
          cors: http://localhost:5173

  PreflightRegister:
    handler: user/Preflight.lambda_handler
    events:
      - http:
          path: user/register
          method: options
          cors: http://localhost:5173

  PreflightVerify:
    handler: user/Preflight.lambda_handler
    events:
      - http:
          path: user/verify
          method: options
          cors: http://localhost:5173
